# Задание 1

In [60]:
import torch
import numpy as np

#####
1. PyTorch предоставляет структуру данных Tensor, которая очень похожа на Numpy nndaray.
2. Разбивает вычисления на части, которые считаются последовательно(представляется это ввиде динамического графа, где каждая вершина независимый код, обрабатывающий свою операцию). Все сложные вычисления происходят на С/С++
3. Каждый torch.Tensor содержит компоненты:
 3.1 grad (значение градиента) или
 3.2 grad_fn(ссылка на функцию вычисления градиента)

In [72]:
x = torch.tensor(4) 
y = torch.tensor(2)
x + y


tensor(6)

### autograd

##### Если для тензора нужно вычислить градиент, тогда requires_grad нужно присвоить значение True, по умолчанию False. Создается динамический граф, в котором автоматически создаются обратные функции, и при вызове .backward() запустится проход по графу в обратную сторону и сосчитается grad

In [56]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x*5
print(y)

z = y.mean()
print(z)

z.backward()
print(x.grad)

tensor([-0.6358, -0.6860,  0.6119], requires_grad=True)
tensor([-3.1788, -3.4299,  3.0594], grad_fn=<MulBackward0>)
tensor(-1.1831, grad_fn=<MeanBackward0>)
tensor([1.6667, 1.6667, 1.6667])


#### Для вектора.

In [59]:
x = torch.ones(3, requires_grad=True)
print(x)
y = x*5
print(y)

g = y+4
print(g)

g.backward(torch.ones_like(g))
print(x.grad)

tensor([1., 1., 1.], requires_grad=True)
tensor([5., 5., 5.], grad_fn=<MulBackward0>)
tensor([9., 9., 9.], grad_fn=<AddBackward0>)
tensor([5., 5., 5.])


### grad

#### тут напишу про градиент, пока сама плохо понимаю, но он есть только в документации, а она вонючая

[1 2 3 4]
[2 4 5 6]


### Autogradient for previous task

#### тут будет градиентный спуск с автоматическим градиентом и наш страрый, для них парочку графиков